### ISSUE TITLE
Error: Please try connecting your wallet again

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#370]
### Issue Category

Other

### What happened?

Multiple users are getting this error message 
<img width="341" alt="Screenshot 2024-01-15 at 13 39 12" src="https://github.com/5afe/safe-support/assets/114049495/f9c23a13-04cc-4b58-b214-0ece9f189e38">
<img width="316" alt="Zrzut ekranu 2024-01-15 133603" src="https://github.com/5afe/safe-support/assets/114049495/e35bc180-989c-4e79-8cdc-4cad41066125">

Users are able to access the Safe, but also gets another error message when trying to sign/execute a tx
![image](https://github.com/5afe/safe-support/assets/114049495/93de5701-f72c-4ea1-8648-0ad6490a8c76)

### Date and time this happened or you first noticed this issue

15-01-2024

### Network

Ethereum Mainnet

### Token Type

None

**Comment by liliya-soroka** [comment]
The team is informed and checking

**Comment by liliya-soroka** [comment]
The RPC was updated. It should work now

**Comment by inahlikenoother** [comment]
> The RPC was updated. It should work now

Thank you! :pray:

**Comment by inahlikenoother** [comment]
> > The RPC was updated. It should work now
> 
> Thank you! 🙏

A few other users are still experiencing the issue, advised them to wait a couple of minutes then try again 🙏

**Comment by liliya-soroka** [comment]
We noticed that ankr rpc returnes 400. the team is checking 
<img width="409" alt="image" src="https://github.com/5afe/safe-support/assets/338622/3acc82f7-68fb-4a01-834f-bb55866eff05">

**Comment by inahlikenoother** [comment]
> We noticed that ankr rpc returnes 400. the team is checking <img alt="image" width="409" src="https://private-user-images.githubusercontent.com/338622/296768768-3acc82f7-68fb-4a01-834f-bb55866eff05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMjU3MzksIm5iZiI6MTcwNTMyNTQzOSwicGF0aCI6Ii8zMzg2MjIvMjk2NzY4NzY4LTNhY2M4MmY3LTY4ZmItNGEwMS04MzRmLWJiNTU4NjZlZmYwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQxMzMwMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTVlZjI2OGNmYzFlMmM0YmVmNzAwZDlkYmUxMjc2MGRhYTdlMDkzNzg5ZGYzOTBkOGQ4MjRlNGZkNWViY2JiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4UJn87bXBpsOlwPaQHxWYTLygWsAOB3otkDQRRtZOEs">

Thank you so much for the quick updates 🙏

**Comment by liliya-soroka** [comment]
The infura rpc was returned back after the issue with it was fixed. As I can see it's stable now .

**Comment by Claire-serveth** [comment]
> The infura rpc was returned back after the issue with it was fixed. As I can see it's stable now .

Thank you @liliya-soroka will check on the users before closing this ticket. 🙏

**Comment by Claire-serveth** [comment]
Since some of the users already confirmed that the issue was indeed fixed on their end, I'll go ahead and close this ticket. Thank you 🙏
